### ISSUE TITLE
Does IPFS have a more active forum or, better yet, a Telegram channel?

### ISSUE THREAD

**Issue by kenCode-de** [ipfs/support#39]
I head up a team of about 40 devs who are actively improving IPFS and we need to work a bit tighter with the IPFS core devs. Would be nice if there was a telegram channel or active forum. 
Please advise, thanx so much :)

**Comment by lidel** [comment]
You may find this "list of available communication channels" useful:
https://github.com/ipfs/ipfs#project-and-community :sparkles:

**Comment by kenCode-de** [comment]
I've never used IRC and the github groups thing seems to be dead. Anyone here using Telegram, or want to start up a Telegram group for IPFS?

**Comment by Kubuxu** [comment]
There are over 800 people on #ipfs channel on freenode IRC network. This is also where many small discussions take place.

**Comment by lidel** [comment]
> the github groups thing seems to be dead

I think you meant _Google_ Group. Indeed, it has low traffic, but it is because most of longer discussions take place in `/issues` of dedicated _Github_ repositories:
- https://github.com/ipfs/faq (https://github.com/ipfs/faq/issues)
- https://github.com/ipfs/support (https://github.com/ipfs/support/issues)
- https://github.com/ipfs/community/ (https://github.com/ipfs/community/issues)

Hope this helps.

**Comment by kenCode-de** [comment]
Yeah cool, I just joined the irc channel and am in the #ipfs room right now, very nice looking chat too, it has audio and video, the whole works. Impressive! :) 
For longer discussions, I will use the github issues url. 
Thanx so much! 

Prost from Munich,
  kenCode
